### ISSUE TITLE
where is MarineC_Jan2014_norm_train.pkl 

### ISSUE THREAD

**Issue by kevinew** [dnguyengithub/MultitaskAIS#13]
Hi guys,

When run python3 calculate_AIS_mean.py, it expose:

tensorflow.python.framework.errors_impl.NotFoundError: /users/local/dnguyen/Datasets/AIS_datasets/MarineC/MarineC_Jan2014_norm/MarineC_Jan2014_norm_train.pkl; No such file or directory

where can I get the pkl data?  thanks.

**Comment by duonginspace** [comment]
Hi, 

_calculate_AIS_mean.py_ calculates the mean of the "4-hot vectors", change the dataset_path to the suitable path (`./data/dataset8/dataset8_train.pkl` for example).
