### ISSUE TITLE
save_outcomes mode line 116

### ISSUE THREAD

**Issue by srinadhu** [dnguyengithub/MultitaskAIS#17]
Hello, @dnguyengithub I was trying to adapt this framework to a new dataset. While pre-processing I removed the ROT and NAV_STT and changed the length parameters wherever required accordingly to 7. I am getting an error when the reshape(-1,4) operation is applied for save_outcomes in line 116 specifically for the D["inp"] one If you have any leads can you tell me the reason?

**Comment by duonginspace** [comment]
Hi, could you be more specific?

**Comment by srinadhu** [comment]
For the mode save_outcomes: the inp and tar shape are (144, 1, 1502) then the shape of np.nonzero(tar[:,0,:])[1] is sometimes like (562,) (518,) (576,) i.e., the reshape(-1,4) operation doesn't always work. What's the need for reshape(-1,4) operation and where all it's dependency is there, let me know?

**Comment by duonginspace** [comment]
Did you modify some parts of the code?
The command _np.nonzero(tar[:,0,:])[1]_ converts the "4-hot vector" representation back to [lat, lon, cog, sog], the output should be (562,) (518,) (576,) (xxx,).

**Comment by srinadhu** [comment]
I did modify some parts, I am running it for Gulf of Mexico part but for a different dataset and there are only 7 attributes unlike 9 attribute in original code, I just removed them [ROT, NAV_STT] in all the global variables. Those are only the changes I made (in pre-processing one) but I am not sure that affects this in the main training part?

**Comment by duonginspace** [comment]
Please make sure that the output of _dataset.create_AIS_dataset_ is "4-hot vector" representation

**Comment by srinadhu** [comment]
Any tips on how to check that? This is my code for the datasets.py file

LAT, LON, SOG, COG, HEADING, TIMESTAMP, MMSI = list(range(7))

DEFAULT_PARALLELISM = 12



def create_AIS_dataset(dataset_path,
                       split,
                       batch_size,
                       data_dim,
                       lat_bins,
                       lon_bins,
                       sog_bins,
                       cog_bins,
                       num_parallel_calls=DEFAULT_PARALLELISM,
                       shuffle=True,
                       repeat=True):
    lat_bins_ = lat_bins; lon_bins_ = lon_bins
    sog_bins_ = sog_bins; cog_bins_ = cog_bins 
    def sparse_AIS_to_dense(msgs_,num_timesteps, mmsis):

        def create_dense_vect(msg,lat_bins = 350, lon_bins = 1050, sog_bins = 30 ,cog_bins = 72): 
            lat, lon, sog, cog = msg[0], msg[1], msg[2], msg[3]
            data_dim = lat_bins + lon_bins + sog_bins + cog_bins
            dense_vect = np.zeros(data_dim)
            dense_vect[int(lat*lat_bins)] = 1.0
            dense_vect[int(lon*lon_bins) + lat_bins] = 1.0
            dense_vect[int(sog*sog_bins) + lat_bins + lon_bins] = 1.0
            dense_vect[int(cog*cog_bins) + lat_bins + lon_bins + sog_bins] = 1.0       
            return dense_vect
   
        dense_msgs = []
        for msg in msgs_:
            dense_msgs.append(create_dense_vect(msg,
                                                lat_bins = lat_bins_,
                                                lon_bins = lon_bins_,
                                                sog_bins = sog_bins_,
                                                cog_bins = cog_bins_))
        dense_msgs = np.array(dense_msgs)
        #print ("dense: " ,dense_msgs.shape)
        return dense_msgs, num_timesteps, mmsis
    
    
    # Load the data from disk.
    try:
        with tf.gfile.Open(dataset_path, "rb") as f:
            raw_data = pickle.load(f)
    except:
        with tf.gfile.Open(dataset_path, "rb") as f:
            raw_data = pickle.load(f, encoding='latin1')
        
    num_examples = len(raw_data)
    dirname = os.path.dirname(dataset_path)
    
    try:
        with open(dirname + "/mean.pkl","rb") as f:
            mean = pickle.load(f)
    except:
        with open(dirname + "/mean.pkl","rb") as f:
            mean = pickle.load(f, encoding='latin1')
        
    def aistrack_generator():
        for k in list(raw_data.keys()):
            #print (raw_data[k].shape)
            tmp = raw_data[k][::2,[LAT,LON,SOG,COG]] # 10 min
            tmp[tmp == 1] = 0.99999
            #print ("tmp", tmp.shape)
            yield tmp, len(tmp), raw_data[k][0,MMSI] 

    dataset = tf.data.Dataset.from_generator(
                                  aistrack_generator,
                                  output_types=(tf.float64, tf.int64, tf.int64))
    
    if repeat: dataset = dataset.repeat()
    if shuffle: dataset = dataset.shuffle(num_examples)
    
    dataset = dataset.map(
            lambda msg_, num_timesteps, mmsis: tuple(tf.py_func(sparse_AIS_to_dense,
                                                   [msg_, num_timesteps, mmsis],
                                                   [tf.float64, tf.int64, tf.int64])),
                                                num_parallel_calls=num_parallel_calls)
    
    # Batch sequences togther, padding them to a common length in time.
    dataset = dataset.padded_batch(batch_size,
                                 padded_shapes=([None, data_dim], [], []))
    
    
    def process_AIS_batch(data, lengths, mmsis):
        """Create mean-centered and time-major next-step prediction Tensors."""
        data = tf.to_float(tf.transpose(data, perm=[1, 0, 2]))
        lengths = tf.to_int32(lengths)
        mmsis = tf.to_int32(mmsis)
        targets = data
        
        # Mean center the inputs.
        inputs = data - tf.constant(mean, dtype=tf.float32,
                                    shape=[1, 1, mean.shape[0]])
        # Shift the inputs one step forward in time. Also remove the last 
        # timestep so that targets and inputs are the same length.
        inputs = tf.pad(data, [[1, 0], [0, 0], [0, 0]], mode="CONSTANT")[:-1] 
        # Mask out unused timesteps.
        inputs *= tf.expand_dims(tf.transpose(
            tf.sequence_mask(lengths, dtype=inputs.dtype)), 2)
        #print ("inputs and targets", inputs.shape, targets.shape)
        return inputs, targets, lengths, mmsis
    
    dataset = dataset.map(process_AIS_batch,
                          num_parallel_calls=num_parallel_calls)

    dataset = dataset.prefetch(50)
    itr = dataset.make_one_shot_iterator()
    inputs, targets, lengths, mmsis = itr.get_next()

    return inputs, targets, lengths, mmsis, tf.constant(mean, dtype=tf.float32)
