### ISSUE TITLE
Some queries regarding contrario.py

### ISSUE THREAD

**Issue by srinadhu** [dnguyengithub/MultitaskAIS#19]
Thanks, @dnguyengithub for answering all my queries patiently. In the file Contrario.py can you please  tell me what's the numbers subtracting and dividing by 300 mean and how are they related to min lat, max lat, min long, max long. I understand that they are mapping indices properly but it's not very clear. Thank you.

**Comment by duonginspace** [comment]
Yes, that how we map the "4-hot vector" to the mean and the std  log_prob map. 

I think lines 195-218 in multitaskAIS.py would help you understand the mapping.
