### ISSUE TITLE
 NewRandomAccessFile failed to Create/Open

### ISSUE THREAD

**Issue by amuni1234** [dnguyengithub/MultitaskAIS#21]
Hi,

I tried running the code in my system. Initially it threw the following error-

DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from flags_config.  Description from first occurrence: directory to write logfiles 

After that i tried to clear all the flags before each iterations.
Now it throws the followin error-
NotFoundError: NewRandomAccessFile failed to Create/Open: ./data/dataset8/dataset8_train.pkl : The system cannot find the path specified.
; No such process
 Even I downloaded the file again and ran it . But the same error persists.

Would you please help me in getting this resolved

**Comment by duonginspace** [comment]
Hi,
Which OS are you using? (window or linux).
I cannot replicate this bug on my server (Linux).

**Comment by amuni1234** [comment]
I am using Windows..I found a temporary fix to get the code running. I deleted all flags before being declared in flag_config.py .i added following lines - 
def del_all_flags(FLAGS):
    flags_dict = FLAGS._flags()    
    keys_list = [keys for keys in flags_dict]    
    for keys in keys_list:
        FLAGS.__delattr__(keys)

del_all_flags(tf.app.flags.FLAGS)

The code ran after that. But the training is takiing long time now. It has been 200000 steps and the code is still running. Please let me know if  i did something wrong in doing so. And how much of running time it should take for a sysy=tem with 1060ti GPU . How many iterations should it normally take for training .I used the dataset provided in the link in the data folder

**Comment by duonginspace** [comment]
Hi,
Happy to know that you solved the flag problem.

About the training time, you should manually stop the training process when the model converge. 

Good luck!

**Comment by amuni1234** [comment]
Hi,
Thanks for the information. Curious to know if anyone who had this error earlier did it in any other way.
Apart from that how do we stop the training process manually. I mean killing the  process running  in the middle would prevent us from testing the model and  trajectory reconstruction as all of them are in a single script(multitaskAIS.py)

With regards,
Abhishek Muni

**Comment by amuni1234** [comment]
Hi,
I saw the instruction steps to train and then run the submodules. Would you please help doing the same in windows for example where exactly to change the parameters if we want to stop training manually and  perform the other tasks like anomaly detection or trajectory reconstruction mentioned

**Comment by dnguyengithub** [comment]
Hi,
To you can modify the value of the flags in flags_config.py.
Duong

**Comment by duonginspace** [comment]
Hi,
You can modify the value of the flags in ` flags_config.py`.
Duong
