### ISSUE TITLE
About the "Vessel type identification submodel"

### ISSUE THREAD

**Issue by tangkun-github** [dnguyengithub/MultitaskAIS#23]
Hi, Dear Teacher:
       Firstly, please forgive me for my poor english. Then, I want to ask a question about the "Vessel type identification submodel".
      As I am not understand the  deep learning, so when I trying to run the "vessel_type_classification.py" program file, I find that the program need two pkl file which names are "MarineC_Jan2014_norm_train_rnn_state.pkl" and "MarineC_Jan2014_norm_test_rnn_state.pkl". I used the preprocessed "train.pkl" and "test.pkl" to instead them, but I am failed.
      Are you mind provide the two files? Better if you could provide other solutions.

Thanks for your early reply.

Best Regards,
send by Seven

**Comment by duonginspace** [comment]
Hi,
The input of the vessel type identification submodel is the hidden states of the embedding layer, (and not the ais messages). 
These files are two large, I can not upload them to github.
You can create them using generate_vessel_type_dataset py.

**Comment by tangkun-github** [comment]
Thank you!!!

**Comment by edowson** [comment]
@dnguyengithub `git lfs` should be able to handle uploading large files.

```bash
git lfs install
git lfs track '*.zip'
```

See: https://help.github.com/en/github/managing-large-files/configuring-git-large-file-storage

**Comment by duonginspace** [comment]
Hi @edowson ,
Thank you very much! However, I dont want to push large files to github (in order to help people clone this repository easily). 
 You can create the inputs of the vessel type identification submodel locally using `generate_vessel_type_dataset py`.
