### ISSUE TITLE
how to use in tensorflow 2.1.0 version

### ISSUE THREAD

**Issue by yessyes** [dnguyengithub/MultitaskAIS#24]
Hi, Dear Teacher:
Firstly, please forgive me for my poor english. Then, I want to ask a question about the "tensorflow 2.1.0 version".
The code is TensorFlow version 1, but how do I work with version 2?
Better if you could provide other solutions.

Thanks for your early reply.

Best Regards,
send by Gwanho

**Comment by duonginspace** [comment]
Hello,

At this moment, MultitaskAIS is available in Tensorflow 1.x only.
