### ISSUE TITLE
Embedding training parameters - max_steps

### ISSUE THREAD

**Issue by JSchuurmans** [dnguyengithub/MultitaskAIS#3]
Thank you @dnguyengithub, for providing the code of your paper. 

When trying to reproduce your results using dataset8, the following questions arise:
1. What was the log-likelihood of your model on dataset8 (Ushant)?
    1. In the paper you indicate a log-likelihood of -6.5 for the Gulf of Mexico. For me the log-likelihood on the Ushant training seems to converge around -5 per timestep, but does not yield proper trajectories. 
1. How long did you train for in updating steps and time?
    1. In the code you set the default for `max_steps` to `int(1e9)`. Do you let it train until this limit or did you use early stopping?
    1. Furthermore, could you also give an indication of the training time (and hardware setup) that you had for both dataset8 and the marinecadastre data sets?

**Comment by duonginspace** [comment]
Hi,

1. On the Brittany (Ushant) dataset, the Embedding layer converges around -5.2, after ~480000 time steps. 
2. No we didnt let it train until max_steps. The purpose of setting max_steps = 1e9 is to let the Embedding layer runs "forever", we manually stop the training when we observe that the model converge. 

We havent tested the Trajectory reconstruction module on the Brittany dataset yet. The most important of the proposed model is anomaly detection. We spent a very little time on trajectory reconstruction and vessel type identification. These two tasks were added in the paper to demonstrate that with the proposed architecture, we can easily add any task-specific sub-module to the system without any effort. 

You can notice that the Trajectory reconstruction module was poorly implemented. We believed that there is much room for improvement there, especially how to embed/decode the "four-hot vector".
