### ISSUE TITLE
predicting in trajectory reconstruction

### ISSUE THREAD

**Issue by JSchuurmans** [dnguyengithub/MultitaskAIS#4]
@dnguyengithub, I'm trying to figure out how you are predicting trajectories when `--mode traj_reconstruction`. 
* If I understand correctly there are two different prediction methods used. One for observed data, and one for hold-out sequence.
    * The reconstruction in the observed data, is simply a one-step ahead prediction based on the observed position (and other data) in a previous time step, t-1 (and hidden and latent variables from t-1).
    * The predictions made during the hold-out sample are prediction made multiple time steps into the future (depending on how far away they are from the last observed position). The **predictions multiple time steps into the future is where the confusion arises**. 

If I understand correctly from your code you set the input array to zeros when you are in a holdout sample. Meaning the RNN depends on the hidden and latent state to make a prediction. 
**Why is the previous predicted position (and other data) not used as input for the next prediction?** Can both methods be used to reconstruct trajectories over multiple time steps where data is missing? Is one approach better than the other?

Below is a summary of your code, to help me investigate how reconstructions are made. Most important is the `runners.create_eval_graph` function. Inside this function, the following snippet is where the distinction is made between regular and hold-out data. For regular data, the `cur_inputs` are used. When the data is supposed to be in the hold-out period, `cur_inputs` is changed to be equal to `while_samples`.
```
if config.missing_data:
     cur_inputs = tf.cond(tf.logical_and(t < max_seq_len - 6,t >= max_seq_len - 18),
         lambda: while_samples, 
         lambda: cur_inputs)
```
The `while_samples` are an input for the function `while_step`. When the `while_step` function is called, `while_samples` input is defined as `init_targets`. In its turn `init_targets` is a tuple of two `tf.zeros` arrays. **Why is `init_targets` a tuple of `target_sampled0` and `target_true0` (the two `tf.zeros` arrays)?** And not based on the previous predictions for example.
```
##############################
# runners.py
##############################
def create_eval_graph(inputs, targets, lengths, model, config):

	max_seq_len = tf.reduce_max(lengths)
	...
	target_sampled0 = tf.zeros(shape = [batch_size*num_samples, config.data_dim], dtype = tf.float32)
        target_true0 = tf.zeros(shape = [batch_size*num_samples, config.data_dim], dtype = tf.float32)
        init_targets = (target_sampled0, target_true0)
        def while_step(t, rnn_state, tas, accs, while_samples):
		...
		if config.missing_data:
                    cur_inputs = tf.cond(tf.logical_and(t < max_seq_len - 6,t >= max_seq_len - 18),
                                 lambda: while_samples, 
                                 lambda: cur_inputs)
        ...
	_, _, tas, accs, new_sample = tf.while_loop(while_predicate,
                                    while_step,
                                    loop_vars=(t0, init_states, tas, accs, init_targets),
                                    parallel_iterations=parallel_iterations,
                                    swap_memory=swap_memory)
    return track_sample, track_true, log_weights, ll_per_t, final_log_weights/tf.to_float(lengths), rnn_state_tf, rnn_latent_tf, rnn_out_tf

def create_dataset_and_model(config, split, shuffle, repeat):
    inputs, targets, lengths, mmsis, mean = datasets.create_AIS_dataset(...)
    ...
    return inputs, targets, mmsis, lengths, model

###############################
# multitaskAIS.py
###############################
if config.mode in ['save_outcomes','traj_reconstruction']:
	...
	inputs, targets, mmsis, lengths, model = runners.create_dataset_and_model(config, config.split, shuffle=False, repeat=False)
	if config.mode =='traj_reconstruction'
		config.missing_data = True

	track_sample, track_true, log_weights, ll_per_t, ll_acc,_,_,_\
            = runners.create_eval_graph(inputs, targets, lengths, model, config)
    ...
...
if ...
elif config.mode =='traj_reconstruction'
    ...
    save_dir = ...
    ...
    for d_i in tqdm(list(range(dataset_size))):
         tar, mmsi, dense_sample, ll_t, ll_tracks = sess.run([targets, mmsis, track_sample, ll_per_t, ll_acc])
         if len(tar) < config.min_duration:
            continue
        
        sparse_tar = np.nonzero(np.squeeze(tar))[1].reshape(-1,4)
        for d_i_sample in range(config.num_samples):
        	...
        	plt.plot(sparse_tar[-18:-6,1],sparse_tar[-18:-6,0],'ro')
        	...
        	logit_lat = np.argmax(dense_sample[:,d_i_sample,0:config.lat_bins], axis = 1)
        	logit_lon = np.argmax(dense_sample[:,d_i_sample,config.lat_bins:config.lat_bins+config.lon_bins], axis = 1) + config.lat_bins
        	plt.plot(logit_lon[1:],logit_lat[1:],'b')
        	plt.plot(logit_lon[-17:-5],logit_lat[-17:-5],'r')
```

**Comment by duonginspace** [comment]
Hi, 
We have two options to implement multi-step-ahead prediction:

1. Use the hidden states of the LSTM and the lattent variables only.
2. Apply one-step-ahead prediction, then use the predicted position as the input of the next prediction.

You can use either option 1 or option 2.  We chose option 1 because it performed slightly better. However, as stated in #3 , we didnt spend much time on this task. Please let us know if you figure out which predicting strategy is better.
