### ISSUE TITLE
input tas in while_step function

### ISSUE THREAD

**Issue by JSchuurmans** [dnguyengithub/MultitaskAIS#5]
@dnguyengithub, relating to #4 . 
Within the file `runners.py` and the function `create_eval_graph`.
The function `while_step` is defined and called by `tf.while_loop`.

When it is called, one of the arguments passed is `tas`.

However, `tas` is not used inside `while_step`. Could it be that the following line inside `while_step`:
```
cur_inputs, cur_mask = nested.read_tas([inputs_ta, mask_ta], t)
```
should be changed to:
```
cur_inputs, cur_mask = nested.read_tas(tas, t)
```
???

Otherwise could you please explain why `tas` is not used. And `inputs_ta`, `mask_ta` are only defined once, outside of `while_step`?
Relating to #4 why they are changed to `tf.zeros` arrays when an observation belongs to the hold-out sample.

**Comment by duonginspace** [comment]
Hi,
This code is a quick-and-dirty version of MultitaskAIS. 
I probably forget to delete this argument when copy-paste from other function.

```inputs_ta``` and ```mask_ta``` are "global" variables.
