### ISSUE TITLE
Inconsistent area bounds between `csv2pkl.py`, `data_preprocessing.py`, `flags_config.py`

### ISSUE THREAD

**Issue by JSchuurmans** [dnguyengithub/MultitaskAIS#7]
`data_preprocessing.py` and `flags_config.py` define:
LAT_MIN = 26.5
LAT_MAX = 30.0
LON_MIN = -97.5
LON_MAX = -87

while `csv2pkl.py` uses:
LAT_MIN = 27
LAT_MAX = 30.0
LON_MIN = -98
LON_MAX = -88

Given the figures in the paper, I assume the bounds defined in `data_preprocessing.py` and `flags_config.py` are correct and `csv2pkl.py` needs to be adjusted?

**Comment by duonginspace** [comment]
Hi, 

Yes, the bounds that we used in the paper are:
LAT_MIN = 26.5
LAT_MAX = 30.0
LON_MIN = -97.5
LON_MAX = -87
