### ISSUE TITLE
interpolation of angles

### ISSUE THREAD

**Issue by JSchuurmans** [dnguyengithub/MultitaskAIS#9]
In the interpolation function `interpolate( )`, defined in utils.py, COG and HEADING are interpolated as follows:

`course_interp = (track[apos,COG] - track[bpos,COG] )*(dt_interp/dt_full) + track[bpos,COG]`
`heading_interp = (track[apos,HEADING] - track[bpos,HEADING])*(dt_interp/dt_full) + track[bpos,HEADING]`

This updates the before position with a weighted difference between 'after' and 'before'.

The issue arises when the angle (in degrees) goes through north. E.g. when moving from 350 to 10: (10-350)*.5 + 350 = 180 (instead of 0). The above implementation goes the long way round the compass.

**Comment by JSchuurmans** [comment]
This can be resolved by calculating the difference between angles as follows:
`( ((track[apos,COG] - track[bpos,COG])+180) % 360 - 180 )`, then adding 360 to always make the angle positive and `%360` at the end to make sure the angle is between [0,360).

This results in the following solution (to be implemented in branch python3):
```
course_interp = (( ((track[apos,COG] - track[bpos,COG])+180) % 360 - 180 )*(dt_interp/dt_full) + track[bpos,COG] + 360) % 360
heading_interp = (( ((track[apos,HEADING] - track[bpos,HEADING])+180) % 360 - 180 )*(dt_interp/dt_full) + track[bpos,HEADING] + 360 ) % 360
```

**Comment by duonginspace** [comment]
Yes you're right. 
Thank you for that.

**Comment by JSchuurmans** [comment]
The solution I suggested does not work with `track[apos,COG] = 10` and `track[bpos,COG] = 350`.
